// Dev fixture for visual verification before aion/7 lands.
const devExpressionData = <String, dynamic>{
  'planets': [
    {
      'id': 'sun',
      'name': 'Sun',
      'longitude': 135.5,
      'sign': 'Leo',
      'sign_index': 4,
      'degree_in_sign': 15.5,
      'retrograde': false,
      'nakshatra': 'Magha',
      'nakshatra_pada': 2,
      'house': 1,
    },
    {
      'id': 'moon',
      'name': 'Moon',
      'longitude': 45.2,
      'sign': 'Taurus',
      'sign_index': 1,
      'degree_in_sign': 15.2,
      'retrograde': false,
      'nakshatra': 'Rohini',
      'nakshatra_pada': 3,
      'house': 10,
    },
    {
      'id': 'mars',
      'name': 'Mars',
      'longitude': 200.0,
      'sign': 'Libra',
      'sign_index': 6,
      'degree_in_sign': 20.0,
      'retrograde': true,
      'nakshatra': 'Swati',
      'nakshatra_pada': 1,
      'house': 3,
    },
    {
      'id': 'mercury',
      'name': 'Mercury',
      'longitude': 120.0,
      'sign': 'Leo',
      'sign_index': 4,
      'degree_in_sign': 0.0,
      'retrograde': false,
      'nakshatra': 'Magha',
      'nakshatra_pada': 1,
      'house': 1,
    },
    {
      'id': 'jupiter',
      'name': 'Jupiter',
      'longitude': 280.0,
      'sign': 'Capricorn',
      'sign_index': 9,
      'degree_in_sign': 10.0,
      'retrograde': false,
      'nakshatra': 'Shravana',
      'nakshatra_pada': 2,
      'house': 6,
    },
    {
      'id': 'venus',
      'name': 'Venus',
      'longitude': 160.0,
      'sign': 'Virgo',
      'sign_index': 5,
      'degree_in_sign': 10.0,
      'retrograde': false,
      'nakshatra': 'Hasta',
      'nakshatra_pada': 1,
      'house': 2,
    },
    {
      'id': 'saturn',
      'name': 'Saturn',
      'longitude': 330.0,
      'sign': 'Pisces',
      'sign_index': 11,
      'degree_in_sign': 0.0,
      'retrograde': true,
      'nakshatra': 'Purva Bhadrapada',
      'nakshatra_pada': 4,
      'house': 8,
    },
    {
      'id': 'rahu',
      'name': 'Rahu',
      'longitude': 70.0,
      'sign': 'Gemini',
      'sign_index': 2,
      'degree_in_sign': 10.0,
      'retrograde': true,
      'nakshatra': 'Ardra',
      'nakshatra_pada': 1,
      'house': 11,
    },
    {
      'id': 'ketu',
      'name': 'Ketu',
      'longitude': 250.0,
      'sign': 'Sagittarius',
      'sign_index': 8,
      'degree_in_sign': 10.0,
      'retrograde': true,
      'nakshatra': 'Moola',
      'nakshatra_pada': 1,
      'house': 5,
    },
  ],
  'ascendant': {'sign_index': 4, 'longitude': 130.0},
  'houses': [
    {'number': 1, 'sign_index': 4, 'cusp_longitude': 130.0},
    {'number': 2, 'sign_index': 5, 'cusp_longitude': 160.0},
    {'number': 3, 'sign_index': 6, 'cusp_longitude': 190.0},
    {'number': 4, 'sign_index': 7, 'cusp_longitude': 220.0},
    {'number': 5, 'sign_index': 8, 'cusp_longitude': 250.0},
    {'number': 6, 'sign_index': 9, 'cusp_longitude': 280.0},
    {'number': 7, 'sign_index': 10, 'cusp_longitude': 310.0},
    {'number': 8, 'sign_index': 11, 'cusp_longitude': 340.0},
    {'number': 9, 'sign_index': 0, 'cusp_longitude': 10.0},
    {'number': 10, 'sign_index': 1, 'cusp_longitude': 40.0},
    {'number': 11, 'sign_index': 2, 'cusp_longitude': 70.0},
    {'number': 12, 'sign_index': 3, 'cusp_longitude': 100.0},
  ],
};
